from PyQt6 import QtCore, QtGui, QtWidgets
from People import People
from nhanvien import nhanvien
List=nhanvien()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 626)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 260, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.m1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.m1.setGeometry(QtCore.QRect(60, 310, 93, 28))
        self.m1.setObjectName("m1")
        self.h1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.h1.setGeometry(QtCore.QRect(60, 350, 93, 28))
        self.h1.setObjectName("h1")
        self.n1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.n1.setGeometry(QtCore.QRect(60, 390, 93, 28))
        self.n1.setObjectName("n1")
        self.c1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.c1.setGeometry(QtCore.QRect(60, 440, 93, 28))
        self.c1.setObjectName("c1")
        self.l1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(60, 490, 93, 28))
        self.l1.setObjectName("l1")
        self.m2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.m2.setGeometry(QtCore.QRect(220, 310, 93, 28))
        self.m2.setObjectName("m2")
        self.m3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.m3.setGeometry(QtCore.QRect(420, 310, 93, 28))
        self.m3.setObjectName("m3")
        self.m4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.m4.setGeometry(QtCore.QRect(600, 310, 93, 28))
        self.m4.setObjectName("m4")
        self.h2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.h2.setGeometry(QtCore.QRect(220, 350, 93, 28))
        self.h2.setObjectName("h2")
        self.h3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.h3.setGeometry(QtCore.QRect(420, 350, 93, 28))
        self.h3.setObjectName("h3")
        self.h4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.h4.setGeometry(QtCore.QRect(600, 350, 93, 28))
        self.h4.setObjectName("h4")
        self.c4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.c4.setGeometry(QtCore.QRect(600, 440, 93, 28))
        self.c4.setObjectName("c4")
        self.c2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.c2.setGeometry(QtCore.QRect(220, 440, 93, 28))
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.c3.setGeometry(QtCore.QRect(420, 440, 93, 28))
        self.c3.setObjectName("c3")
        self.l4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(600, 490, 93, 28))
        self.l4.setObjectName("l4")
        self.l2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(220, 490, 93, 28))
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(420, 490, 93, 28))
        self.l3.setObjectName("l3")
        self.n2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.n2.setGeometry(QtCore.QRect(220, 390, 93, 28))
        self.n2.setObjectName("n2")
        self.n3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.n3.setGeometry(QtCore.QRect(420, 390, 93, 28))
        self.n3.setObjectName("n3")
        self.n4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.n4.setGeometry(QtCore.QRect(600, 390, 93, 28))
        self.n4.setObjectName("n4")
        self.thoat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.thoat.setGeometry(QtCore.QRect(320, 540, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thoat.setFont(font)
        self.thoat.setObjectName("thoat")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 20, 681, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.tableWidget.setColumnCount(5)

        # Tính toán độ rộng cột cho mỗi cột
        table_width = self.tableWidget.width()
        column_width = table_width / 5  # 5 là số lượng cột
        column_width = int(column_width)  # Chuyển đổi thành số nguyên

        # Đặt độ rộng cho mỗi cột
        for column in range(5):
            self.tableWidget.setColumnWidth(column, column_width)

        # Đặt tiêu đề cho các cột
        self.tableWidget.setHorizontalHeaderLabels(["Mã nhân viên", "Họ và Tên", "Ngày sinh", "Chức vụ", "Lương"])
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sort"))
        self.label.setText(_translate("MainWindow", "SelectionSort"))
        self.label_2.setText(_translate("MainWindow", "InsectionSort"))
        self.label_3.setText(_translate("MainWindow", "QuickSort"))
        self.label_4.setText(_translate("MainWindow", "MergeSort"))
        self.m1.setText(_translate("MainWindow", "Mã nhân viên"))
        self.h1.setText(_translate("MainWindow", "Họ và tên"))
        self.n1.setText(_translate("MainWindow", "Ngày sinh"))
        self.c1.setText(_translate("MainWindow", "Chức vụ"))
        self.l1.setText(_translate("MainWindow", "Lương"))
        self.m2.setText(_translate("MainWindow", "Mã nhân viên"))
        self.m3.setText(_translate("MainWindow", "Mã nhân viên"))
        self.m4.setText(_translate("MainWindow", "Mã nhân viên"))
        self.h2.setText(_translate("MainWindow", "Họ và tên"))
        self.h3.setText(_translate("MainWindow", "Họ và tên"))
        self.h4.setText(_translate("MainWindow", "Họ và tên"))
        self.c4.setText(_translate("MainWindow", "Chức vụ"))
        self.c2.setText(_translate("MainWindow", "Chức vụ"))
        self.c3.setText(_translate("MainWindow", "Chức vụ"))
        self.l4.setText(_translate("MainWindow", "Lương"))
        self.l2.setText(_translate("MainWindow", "Lương"))
        self.l3.setText(_translate("MainWindow", "Lương"))
        self.n2.setText(_translate("MainWindow", "Ngày sinh"))
        self.n3.setText(_translate("MainWindow", "Ngày sinh"))
        self.n4.setText(_translate("MainWindow", "Ngày sinh"))
        self.thoat.setText(_translate("MainWindow", "Thoát"))

